language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=pyperlin -m unittest -v pyperlin.tests
- coverage report -m --skip-covered --skip-empty
after_success:
- coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: fTm7+YvlPdc5MMJ9YSbmMW3N15GBs6aY5xX4ChESSJa/3YHKzKa9kKD2Llo6oW3cB05HJ1ucKODHjm9t/adJrqbNgZloRRBbT7oIGJQP0RZVPBx7xaEK2E5kxepREW7SR/Qs/Dn+MZB7r3F2RWwkspD2H9Lnd2fP7R6msiHzNO+Q113Ijog4SCHZilItJ7dD4eqnAGtTYFv1LB6b1Sv40ck6XiUgnMqKIMx3Os37ruMuvUec1Y24QzC2wTI2UjfNZM4JJU/xWuXC+i2qgo00maHV+qNCzgksPt8YfDpI3s56u/HzztkHUUyk28oHs5RTMgYkZx0rW/Kk9b7QoTOzALbcn8n0DpH9NKWcIu/fRAcdzqMfmfDRVsh7vLt4bEVwVE/DOTaQBOVjFT8hm+BeDlw8G3C1lYPXC+wrbkAmPP1NMTzJiAIhwMfYRGTQGh1ugTr6/3Vmma+qImAc6tMd7emBsWHPfYs5CvmVsz8oQdgJ1yKa6tMltuQKthtQyUr5knsvFx/P2/PTlMnv40RKC+RbGcl6UtpH2Yhf51fo8uYEr8MqIzMa/H2pruyUZ181F4Hr636B+myavncgUml1tqIDtLf4q+lef8VKT94zqUfuIAS2eQoJY5YTxqsJY+ocX4v0pyNjQ2Yhm9UL7UuIcFGTcM1YrkmfIHXI8J+zAvc=
  skip_existing: true
